### ISSUE TITLE
Issue with directives

### ISSUE THREAD

**Issue by soulr3aver** [fintechstudios/angularjs-mdc#1]
i used your example code and i put it into a directive with a controller attached to it

``` javascript
         <mdc-textfield dense="isDense">
            <input id="my-textfield"
                   name="email" aria-controls="my-textfield-helptext"
                   data-demo-no-auto-js autocomplete="email"
                   ng-disabled="isDisabled" ng-required="isRequired" ng-model="fullDemoValue">
            <label for="my-textfield">Email Address</label>
          </mdc-textfield>
```
when the component initialize he give me back and error 
 
```
angular.js:13236 TypeError: Cannot set property '$render' of undefined
    at MdcTextfieldController.rebuild (https://localhost:44304/areas/application/content/common/materialangularjs/angularjs-mdc.js:13994:39)
    at HTMLDocument.<anonymous> (https://localhost:44304/areas/application/content/common/materialangularjs/angularjs-mdc.js:13943:14)

```
at this line 
```javascript
this.inputModelCtrl = angular.element(this.mdc.input_).controller('ngModel');
```

**Comment by dpraul** [comment]
This should be resolved in the latest version! (Do note there have been large changes to `mdc-text-field` when you update)
